package org.zionusa.base.enums;

public enum EApplicationRole {
    // Events - General Roles (COG or WLU)
    EVENT_DEFAULT_ADMIN("EVENT_DEFAULT_ADMIN"),
    EVENT_DEFAULT_ASSISTANT("EVENT_DEFAULT_ASSISTANT"),
    EVENT_DEFAULT_AUDIO_VISUAL("EVENT_DEFAULT_AUDIO_VISUAL"),
    EVENT_DEFAULT_AUDIO_VISUAL_ADMIN("EVENT_DEFAULT_AUDIO_VISUAL_ADMIN"),
    EVENT_DEFAULT_GA("EVENT_DEFAULT_GA"),
    EVENT_DEFAULT_EDITORIAL("EVENT_DEFAULT_EDITORIAL"),
    EVENT_DEFAULT_EDITORIAL_ADMIN("EVENT_DEFAULT_EDITORIAL_ADMIN"),
    EVENT_DEFAULT_GRAPHIC_DESIGNER("EVENT_DEFAULT_GRAPHIC_DESIGNER"),
    EVENT_DEFAULT_GRAPHIC_DESIGNER_ADMIN("EVENT_DEFAULT_GRAPHIC_DESIGNER_ADMIN"),
    EVENT_DEFAULT_MANAGER("EVENT_DEFAULT_MANAGER"),
    EVENT_DEFAULT_PHOTOGRAPHER("EVENT_DEFAULT_PHOTOGRAPHER"),
    EVENT_DEFAULT_PHOTOGRAPHER_ADMIN("EVENT_DEFAULT_PHOTOGRAPHER_ADMIN"),
    EVENT_DEFAULT_PUBLIC_RELATIONS("EVENT_DEFAULT_PUBLIC_RELATIONS"),
    EVENT_DEFAULT_REGISTRAR("EVENT_DEFAULT_REGISTRAR"),
    EVENT_DEFAULT_REPRESENTATIVE("EVENT_DEFAULT_REPRESENTATIVE"),
    EVENT_DEFAULT_SPOKESPERSON("EVENT_DEFAULT_SPOKESPERSON"),
    EVENT_DEFAULT_VIDEOGRAPHER("EVENT_DEFAULT_VIDEOGRAPHER"),
    EVENT_DEFAULT_VIDEOGRAPHER_ADMIN("EVENT_DEFAULT_VIDEOGRAPHER_ADMIN"),

    // Events - ASEZ / IUBA
    EVENT_ASEZ_IUBA_ADMIN("EVENT_ASEZ_IUBA_ADMIN"),
    EVENT_ASEZ_IUBA_ASSISTANT("EVENT_ASEZ_IUBA_ASSISTANT"),
    EVENT_ASEZ_IUBA_AUDIO_VISUAL("EVENT_ASEZ_IUBA_AUDIO_VISUAL"),
    EVENT_ASEZ_IUBA_AUDIO_VISUAL_ADMIN("EVENT_ASEZ_IUBA_AUDIO_VISUAL_ADMIN"),
    EVENT_ASEZ_IUBA_GA("EVENT_ASEZ_IUBA_GA"),
    EVENT_ASEZ_IUBA_EDITORIAL("EVENT_ASEZ_IUBA_EDITORIAL"),
    EVENT_ASEZ_IUBA_EDITORIAL_ADMIN("EVENT_ASEZ_IUBA_EDITORIAL_ADMIN"),
    EVENT_ASEZ_IUBA_GRAPHIC_DESIGNER("EVENT_ASEZ_IUBA_GRAPHIC_DESIGNER"),
    EVENT_ASEZ_IUBA_GRAPHIC_DESIGNER_ADMIN("EVENT_ASEZ_IUBA_GRAPHIC_DESIGNER_ADMIN"),
    EVENT_ASEZ_IUBA_MANAGER("EVENT_ASEZ_IUBA_MANAGER"),
    EVENT_ASEZ_IUBA_PHOTOGRAPHER("EVENT_ASEZ_IUBA_PHOTOGRAPHER"),
    EVENT_ASEZ_IUBA_PHOTOGRAPHER_ADMIN("EVENT_ASEZ_IUBA_PHOTOGRAPHER_ADMIN"),
    EVENT_ASEZ_IUBA_PUBLIC_RELATIONS("EVENT_ASEZ_IUBA_PUBLIC_RELATIONS"),
    EVENT_ASEZ_IUBA_REGISTRAR("EVENT_ASEZ_IUBA_REGISTRAR"),
    EVENT_ASEZ_IUBA_REPRESENTATIVE("EVENT_ASEZ_IUBA_REPRESENTATIVE"),
    EVENT_ASEZ_IUBA_SPOKESPERSON("EVENT_ASEZ_IUBA_SPOKESPERSON"),
    EVENT_ASEZ_IUBA_VIDEOGRAPHER("EVENT_ASEZ_IUBA_VIDEOGRAPHER"),
    EVENT_ASEZ_IUBA_VIDEOGRAPHER_ADMIN("EVENT_ASEZ_IUBA_VIDEOGRAPHER_ADMIN"),

    // Events - ASEZ WAO / IWBA
    EVENT_ASEZ_WAO_IWBA_ADMIN("EVENT_ASEZ_WAO_IWBA_ADMIN"),
    EVENT_ASEZ_WAO_IWBA_ASSISTANT("EVENT_ASEZ_WAO_IWBA_ASSISTANT"),
    EVENT_ASEZ_WAO_IWBA_AUDIO_VISUAL("EVENT_ASEZ_WAO_IWBA_AUDIO_VISUAL"),
    EVENT_ASEZ_WAO_IWBA_AUDIO_VISUAL_ADMIN("EVENT_ASEZ_WAO_IWBA_AUDIO_VISUAL_ADMIN"),
    EVENT_ASEZ_WAO_IWBA_GA("EVENT_ASEZ_WAO_IWBA_GA"),
    EVENT_ASEZ_WAO_IWBA_EDITORIAL("EVENT_ASEZ_WAO_IWBA_EDITORIAL"),
    EVENT_ASEZ_WAO_IWBA_EDITORIAL_ADMIN("EVENT_ASEZ_WAO_IWBA_EDITORIAL_ADMIN"),
    EVENT_ASEZ_WAO_IWBA_GRAPHIC_DESIGNER("EVENT_ASEZ_WAO_IWBA_GRAPHIC_DESIGNER"),
    EVENT_ASEZ_WAO_IWBA_GRAPHIC_DESIGNER_ADMIN("EVENT_ASEZ_WAO_IWBA_GRAPHIC_DESIGNER_ADMIN"),
    EVENT_ASEZ_WAO_IWBA_MANAGER("EVENT_ASEZ_WAO_IWBA_MANAGER"),
    EVENT_ASEZ_WAO_IWBA_PHOTOGRAPHER("EVENT_ASEZ_WAO_IWBA_PHOTOGRAPHER"),
    EVENT_ASEZ_WAO_IWBA_PHOTOGRAPHER_ADMIN("EVENT_ASEZ_WAO_IWBA_PHOTOGRAPHER_ADMIN"),
    EVENT_ASEZ_WAO_IWBA_PUBLIC_RELATIONS("EVENT_ASEZ_WAO_IWBA_PUBLIC_RELATIONS"),
    EVENT_ASEZ_WAO_IWBA_REGISTRAR("EVENT_ASEZ_WAO_IWBA_REGISTRAR"),
    EVENT_ASEZ_WAO_IWBA_REPRESENTATIVE("EVENT_ASEZ_WAO_IWBA_REPRESENTATIVE"),
    EVENT_ASEZ_WAO_IWBA_SPOKESPERSON("EVENT_ASEZ_WAO_IWBA_SPOKESPERSON"),
    EVENT_ASEZ_WAO_IWBA_VIDEOGRAPHER("EVENT_ASEZ_WAO_IWBA_VIDEOGRAPHER"),
    EVENT_ASEZ_WAO_IWBA_VIDEOGRAPHER_ADMIN("EVENT_ASEZ_WAO_IWBA_VIDEOGRAPHER_ADMIN"),

    // Multimedia Department
    AUDIO_VISUAL("AUDIO_VISUAL"),
    APP_DEVELOPMENT("APP_DEVELOPMENT"),
    EDITORIAL("EDITORIAL"),
    GRAPHIC_DESIGNER("GRAPHIC_DESIGNER"),
    OVERSEER_APPLICATION_SUPPORT("OVERSEER_APPLICATION_SUPPORT"),
    PHOTOGRAPHER("PHOTOGRAPHER"),
    TRANSLATION("TRANSLATION"),
    VIDEOGRAPHER("VIDEOGRAPHER"),

    // Organization
    ADMIN_ACCESS("ADMIN_ACCESS"),
    ASSOCIATION_ACCESS("ASSOCIATION_ACCESS"),
    ASSOCIATION_LEADER("ASSOCIATION_LEADER"),
    BRANCH_ACCESS("BRANCH_ACCESS"),
    BRANCH_LEADER("BRANCH_LEADER"),
    GROUP_ACCESS("GROUP_ACCESS"),
    GROUP_LEADER("GROUP_LEADER"),
    OVERSEER_ACCESS("OVERSEER_ACCESS"),
    OVERSEER_LEADER("OVERSEER_LEADER"),
    TEAM_ACCESS("TEAM_ACCESS"),
    TEAM_LEADER("TEAM_LEADER"),

    // Study
    STUDY_GA_GRADER("STUDY_GA_GRADER"),
    STUDY_READY_GRADER("STUDY_READY_GRADER"),
    STUDY_TEACHER("STUDY_TEACHER"),
    STUDY_THEOLOGICAL_STUDENT("STUDY_THEOLOGICAL_STUDENT"),
    @Deprecated
    TEACHER_ACCESS("TEACHER_ACCESS"),

    // Other
    CHURCH_LEADER_SHAREPOINT("CHURCH_LEADER_SHAREPOINT"),
    LAST_REFORMER("LAST_REFORMER"),
    SEAL_ONJ("SEAL_ONJ"),
    SEAL_SQT("SEAL_SQT"),

    // Restricted
    APP_STORE_REVIEW("APP_STORE_REVIEW"),
    DASHBOARD_USER("DASHBOARD_USER");

    private final String value;

    EApplicationRole(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public boolean contains(String otherValue) {
        if (otherValue == null) {
            return false;
        }
        return this.value.toUpperCase().contains(otherValue.toUpperCase());
    }

    public boolean is(String otherValue) {
        if (otherValue == null) {
            return false;
        }
        return this.value.equalsIgnoreCase(otherValue);
    }
}
