# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Default windows server build config for windows-latest: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

trigger:
  branches:
    include:
    - development
  paths:
    include:
    - /ZionUSAApiWorkspace/AdminApi/*

pr:
  paths:
    include:
    - /ZionUSAApiWorkspace/AdminApi/*

pool:
  name: 'Azure Pipelines'
  vmImage: 'windows-latest'

steps:

  - task: Gradle@2
    inputs:
      workingDirectory: './'
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      tasks: ':AdminApi:test'