CREATE VIEW dbo.branches_view WITH SCHEMABINDING AS
SELECT b.id,
       b.archived,
       b.hidden,
       b.address,
       b.city,
       b.display_name,
       b.distant,
       b.latitude,
       b.longitude,
       b.leader_id,
       COALESCE(l.display_name, '') AS leader_display_name,
       b.leader_two_id,
       COALESCE(t.display_name, '') AS leader_two_display_name,
       b.name,
       b.parent_branch_id,
       b.picture_file_id,
       b.state_id,
       b.state_full_name,
       b.state_short_name,
       b.type_id,
       b.type_name,
       b.thumbnail_file_id,
       b.main_branch_id,
       b.main_branch_archived,
       b.main_branch_hidden,
       b.main_branch_name,
       b.main_branch_picture_file_id,
       b.main_branch_leader_id,
       b.main_branch_leader_two_id,
       b.main_branch_thumbnail_file_id,
       b.association_id,
       b.association_archived,
       b.association_hidden,
       b.association_name,
       b.association_picture_file_id,
       b.association_leader_id,
       b.association_leader_two_id,
       b.association_pthumbnail_file_id
FROM dbo.branches_view_materialized b
         LEFT JOIN dbo.users_display_view l ON b.leader_id = l.id
         LEFT JOIN dbo.users_display_view t ON b.leader_two_id = t.id
go
